
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("news_like/new", "Create news_like")) ?>
</div>

<?php echo $this->tag->form(array("news_like/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search news_like</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="like_id">Like</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("like_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="news_id">News</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("news_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="mem_id">Mem</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("mem_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="like_date">Like Of Date</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("like_date", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
