
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("news/new", "Create news")) ?>
</div>

<?php echo $this->tag->form(array("news/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search news</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="news_id">News</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("news_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="news_title">News Of Title</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("news_title", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="news_detail">News Of Detail</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("news_detail", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="news_url">News Of Url</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("news_url", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="news_by">News Of By</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("news_by", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="news_level">News Of Level</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("news_level")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="news_date">News Of Date</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("news_date", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="news_pin">News Of Pin</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("news_pin")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
