
<?php echo $this->tag->form("position/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("position", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create position</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="pos_name_th">Pos Of Name Of Th</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("pos_name_th", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="pos_name_en">Pos Of Name Of En</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("pos_name_en", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="pos_order">Pos Of Order</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("pos_order", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="pos_max_member">Pos Of Max Of Member</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("pos_max_member", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
